import { Button, ComboBox, Slider, SpinBox, ListView } from "std-widgets.slint";
import { DiamondSquarePanel, DiamondSquareParams } from "ds_panel.slint";
import { PerlinPanel, PerlinParams } from "perlin_panel.slint";
import { GeneratorType } from "generator_type.slint";
import { GeneratorLayerInfo, GeneratorLayer } from "generator_layer.slint";
import { DebugHelper } from "debug.slint";
import { ExportPanel } from "export_panel.slint";
import { ExportAs } from "export_type.slint";
import { HydraulicErosionPanel, HEParams } from "hydraulic_erosion_panel.slint";

export component AppWindow inherits Window {
    width: 1500px;
    height: 600px;
    title: "Terrain Generator";
    in-out property <int> rows: 512;
    in-out property <int> cols: 512;
    in-out property <[GeneratorLayerInfo]> layers;
    in-out property <int> selected_layer_index: 0;
    in-out property <string> raw_selected_algo;

    in-out property <PerlinParams> current_perlin_params: { seed: 0, scale: 1.0, cell_size: 16 };
    in-out property <DiamondSquareParams> current_ds_params: { seed: 0, roughness: 1 };
    in-out property <GeneratorType> selected_algorithm;

    in property <image> heightmap_image;
    in-out property <bool> terrain_ready: false;
    out property <ExportAs> export_type;
    callback invoke_generate(algorithm: GeneratorType);
    callback add_layer();
    callback combine_layers();
    callback save_terrain(exportAs: ExportAs);
    callback select_layer(index: int);
    callback update_layer(layer_info: GeneratorLayerInfo, index: int);
    callback update_ds_params(params: DiamondSquareParams);
    callback update_perlin_params(params: PerlinParams);
    callback apply_hydraulic_erosion(params: HEParams);

    GridLayout{
        VerticalLayout { 
            width: 25%;

            Text{
                text: "Terrain size";
            }
            GridLayout{
                Text{
                    text: "width";
                }
                SpinBox {
                    minimum: 1;
                    maximum: 2049;
                    step-size: 1;
                    value: root.cols;
                    edited => {
                        root.cols = self.value;
                    }
                }

                Text{
                    text: "height";
                }
                SpinBox {
                    minimum: 1;
                    maximum: 2049;
                    step-size: 1;
                    value: root.rows;
                    edited => {
                        root.rows = self.value;
                    }
                }
            }


            Text { text: "Layers"; }
            DebugHelper {
                algo: root.selected_algorithm;
                exportAs: root.export_type;
                layer: root.selected_layer_index;
            }

            Rectangle {
                background: #c0c0c0;  
                border-radius: 6px;
                clip: true;            

                ListView {
                    for layer[i] in root.layers: GeneratorLayer { layer_info: layer;  
                        selected: root.selected_layer_index == i;
                        clicked => { 
                            if self.selected { 
                                root.select_layer(-1); 
                            }
                            else {
                                root.select_layer(i);
                            }
                        }

                        updated => {
                            root.update_layer(self.layer_info, i);
                            root.select_layer(i);
                        }
                    }
                }
            }
           
            Button {
                text: "Add Layer";
                clicked => {
                    root.add_layer();
                }
            }

            Button {
                text: "Perform combination";
                clicked => {
                    root.combine_layers();
                }
            }
        }
        VerticalLayout {
            if root.selected_layer_index >= 0 : Rectangle {
                if root.selected_algorithm == GeneratorType.perlin : PerlinPanel { 
                    params <=> root.current_perlin_params;

                    params_changed => {
                        if root.selected_layer_index >= 0 {
                            root.update_perlin_params(self.params);
                        }
                    }
                }

                if root.selected_algorithm == GeneratorType.diamondsquare : DiamondSquarePanel {
                    params <=> root.current_ds_params;

                    params_changed => {
                        if root.selected_layer_index >= 0 {
                            root.update_ds_params(self.params);
                        }
                    }
                }
            }
            Rectangle {}

            Button {
                text: "Generate";
                enabled: root.selected_layer_index >= 0;

                clicked => {
                    root.invoke_generate(root.selected_algorithm);
                }
            }
            
        }

        VerticalLayout{
            Image {
                source: root.heightmap_image;
                width: 512px;
                height: 512px;
            }
            Rectangle {}
            ExportPanel {
                ready: root.terrain_ready;
                exportType <=> root.export_type;
                clicked(exportAs) => {
                    root.save_terrain(exportAs);
                }
            }
        }

        VerticalLayout{
            HydraulicErosionPanel {
                active: root.terrain_ready;
                clicked => {root.apply_hydraulic_erosion(self.params);}
            }
        }
    }
}
