import { GeneratorType } from "generator_type.slint";

export component DebugHelper {
    in property <GeneratorType> algo;
    in property <int> layer;

    function algo_to_string(a: GeneratorType) -> string {
        if a == GeneratorType.perlin { return "Perlin Noise"; }
        if a == GeneratorType.diamondsquare { return "Diamond-Square"; }
        return "Unknown";
    }

    VerticalLayout {
        Text {
            text: algo_to_string(root.algo);
        }

        Text {
            text: root.layer;
        }
    }

}